In [1]:
import numpy as np
print(np.__version__)


2.3.1


In [2]:
lst = [1,2,3,4,5,6,6,6]
print(lst)
print("type of list",type(lst))

[1, 2, 3, 4, 5, 6, 6, 6]
type of list <class 'list'>


In [3]:
arr = np.array(lst)
print(arr)
print(type(arr))

[1 2 3 4 5 6 6 6]
<class 'numpy.ndarray'>


In [5]:
lst = list(range(1,10))
print(type(lst))
arr = np.array(lst)
print(arr)

<class 'list'>
[1 2 3 4 5 6 7 8 9]


In [ ]:
print(np.zeros(2))   # print zero


print(np.zeros((5,5)))  # for matrix


print(np.ones((3)))   #print 1


print(np.ones((3,5)))    # for matrix


print(np.linspace(1,10,20)) #print between given range and given element 

[0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [ ]:
arr = np.arange(1,31)

arr.reshape(5,6)  #reshapping the size of array.

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [ ]:
arr = np.random.randint(2,5,9)                # give/print random array output
arr

array([2, 2, 4, 3, 4, 2, 4, 3, 4], dtype=int32)

In [33]:
arr = np.random.randint(2,5,(5,5))                # 
arr

array([[4, 3, 4, 2, 2],
       [3, 3, 4, 4, 4],
       [2, 2, 2, 2, 3],
       [2, 4, 2, 4, 2],
       [2, 2, 4, 3, 2]], dtype=int32)

In [ ]:
arr = np.arange(60).reshape(12,5)
arr.flatten()                                       # to change array to 1D

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])